### ISSUE TITLE
Compatible with Farseek/Streams

### ISSUE THREAD

**Issue by Artemis2017** [kreezxil/Subterranean-Waters#3]
Hello,

i wanted to ask you: Will your mod compatible with Streams/Farseek in the future? It would be very cool!

**Comment by kreezxil** [comment]
Eventually. It's not a priority to resolve this right now.

**Comment by Artemis2017** [comment]
Okay, thank you for the answer. Hope you can fix it in the future! 

One another question: It is compatible with Biomes o Plenty and already existing Worlds?

**Comment by kreezxil** [comment]
it should work fine with biomes o plenty, try it on a test world to make sure it's what you want

**Comment by Artemis2017** [comment]
Okay, thanks!
